# Generated by Django 4.2.30 on 2026-05-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('time_series', 'Time Series'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('data_quality_score', models.FloatField(blank=True, null=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzed', 'Analyzed'), ('trained', 'Trained'), ('error', 'Error')], default='uploaded', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('metrics', models.JSONField()),
                ('pipeline_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expertise_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='api.dataset')),
            ],
        ),
    ]
